name: build

on:
  push:
    # tags:
    #   - v*  # 表示所有v开头的tag
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
      max-parallel: 1
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x # use the latest LTS version of Node
          # cache: "npm"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build app
        if: github.ref != 'refs/heads/main'
        run: yarn build
      - name: Build & deploy app
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn release
